name = "Dot4Docs"
defaultTargets = ["Dot4Docs", "dot4-docs"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.26.0-rc2"

[[require]]
name = "Dot4"
path = ".."

[[lean_lib]]
name = "Dot4Docs"

[[lean_exe]]
name = "dot4-docs"
root = "Dot4DocsMain"
